import "./globals.css";
import Header from "./components/Header";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./providers/SessionProvider";

export const metadata = {
  title: "theBlog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-4xl mx-auto px-4 py-10 font-primary">
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
